// Auth Actions
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const STUDENT_LOADED = 'STUDENT_LOADED';
export const STAFF_LOADED = 'STAFF_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL';
export const STAFF_LOGIN_SUCCESS = 'STAFF_LOGIN_SUCCESS';
export const STAFF_LOGIN_FAIL = 'STAFF_LOGIN_FAIL';
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT';
export const STAFF_LOGOUT = 'STAFF_LOGOUT';

// Alert actions
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Application Actions
export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const GET_APPLICATIONS_BASIC = 'GET_APPLICATIONS_BASIC';
export const GET_APPLICATION = 'GET_APPLICATION';
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const APPROVE_MENTORSHIP = 'APPROVE_MENTORSHIP';
export const APPROVE_MENTOR_SUBJECT = 'APPROVE_MENTOR_SUBJECT';
export const DELETE_APPLICATION = 'DELETE_APPLICATION';
export const APPLICATION_DEL_ERROR = 'APPLICATION_DEL_ERROR';
export const GET_APPLICATIONS_BY_STUDENT = 'GET_APPLICATIONS_BY_STUDENT';
export const ADD_APPLICATION_BY_STUDENT = 'ADD_APPLICATION_BY_STUDENT';
export const APPLICATION_FORM_ERROR = 'APPLICATION_FORM_ERROR';

// User Actions
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const GET_STUDENT_ADMIN = 'GET_STUDENT_ADMIN';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const USER_DEL_ERROR = 'USER_DEL_ERROR';
export const USER_DEFAULT = 'USER_DEFAULT';

// Group Actions
export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUP = 'GET_GROUP';
export const GET_GROUP_ADMIN = 'GET_GROUP_ADMIN';
export const ADD_GROUP = 'ADD_GROUP';
export const ADD_MENTEE_TO_GROUP = 'ADD_MENTEE_TO_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const GROUP_DEL_ERROR = 'GROUP_DEL_ERROR';

// Student Actions
export const GET_STUDENT_INFO = 'GET_STUDENT_INFO';
export const GET_GROUP_FOR_ADD = 'GET_GROUP_FOR_ADD';
export const GET_STUDENTS = 'GET_STUDENTS';
export const ADD_STUDENT = 'ADD_STUDENT';

// Subject Actions
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const SUBJECT_DEL_ERROR = 'SUBJECT_DEL_ERROR';

// Staff Actions
export const GET_STAFF = 'GET_STAFF';
export const ADD_STAFF = 'ADD_STAFF';
